### ISSUE TITLE
Please add support for apply rule

### ISSUE THREAD

**Issue by JosefJezek** [jonathantneal/postcss-nesting#16]
Could you add support for apply rule, check out this links?
- https://github.com/pascalduez/postcss-apply
- https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

``` css
.Navigation {
@nest &--menu {
    --paper-menu-selected-item: {
      color: var(--accent-color);
    };
  }
}
```

This plugin remove semicolon on end of custom property set... :-(

``` css
.Navigation--menu {
    --paper-menu-selected-item: {
      color: var(--accent-color);
    }
  }
```

------------^

Check out the PSK+
https://github.com/StartPolymer/polymer-starter-kit-plus
