### ISSUE TITLE
Concatenative selectors

### ISSUE THREAD

**Issue by keithamus** [jonathantneal/postcss-nesting#17]
Hi @jonathantneal, thanks for making such a cool postcss plugin!

I feel like I've found a potential bug with this. The spec doesn't mention this behaviour specifically, but I'm quite sure it is undesired.

Input:

``` css
.foo {
  color: blue;
  &bar {
    color: red;
  }
}
```

This plugins output:

``` css
.foo {
  color: blue
}
.foobar {
  color: red;
}
```

I would expect to see an error, I think, as the [spec suggests `&` is equivalent of `:matches()`](https://tabatkins.github.io/specs/css-nesting/#selectordef-) - which, to my understanding, means they shouldn't concatenate like this.

Perhaps @tabatkins could clarify this?

**Comment by tabatkins** [comment]
It's wrong, but *only* because type selectors don't have an identifying prefix.  For all other selectors, you *can* just naively concatenate them - `.foo { &.bar {...}}` goes to just `.foo.bar {...}`, for example.  Same for cases where the & is immediately followed by a combinator - naive concatenation works just fine.

So this fails only in two cases:

1. The inner selector puts the `&` at the beginning of a compound selector whose non-& part starts with a type selector, like `.foo { &div {...}}`.
2. The inner selector puts the `&` inside of the compound selector, where the parent selector starts with a type selector, like `div { .foo&.bar {...}}`.

In either case, you just have to do some minor rewriting to make sure the type selector goes first - the first case should result in `div.foo`, the second in `div.foo.bar`.

>  as the spec suggests & is equivalent of :matches() 

You're misreading a bit - if the parent selector uses commas (it's a selector list of length >1), you have to enclose it in a `:matches()` before substituting it into the child, if you're directly synthesizing an equivalent selector.  So `a, b { & c {...}}` becomes `:matches(a, b) c {...}`.  Same if the parent selector has >1 compound selectors and  & isn't in the very first compound selector - `a b { c & {...}}` becomes `c :matches(a b) {...}`.

So `&` isn't *equivalent* to `:matches()`, but constructing equivalent selectors without `&` often requires `:matches()`.

**Comment by taion** [comment]
Is it possible to add some sort of check for this? Right now this is prone to accidental use for cases like `&_title`, which is probably not great.

**Comment by tbremer** [comment]
@taion, that's a good point. Could be a pretty quick RegEx check, using something like:

```javascript
/^&(?: *[a-zA-Z\.#:>\[*+~]|(?:\|\|))/
```

However, there are pieces that (I think, maybe @tabatkins can confirm) this plugin and the spec diverge, the plugin allows for:
```css
a {
    color: blue;
    & & {
        color: orange;
    }
}
```
which compiles to:
```css
a {
    color: blue
}

a a {
    color: orange
}
```

But the Spec doesn't treat the `&` as selector replacement.

**Comment by tbremer** [comment]
The `@nest` rules are a little less terse, so checking validity would have to be thought out a little more, however the spec does call this out specifically as invalid:

```css
.foo {
  color: red;
  @nest & .bar, .baz {
    color: blue;
  }
}
/* Invalid because not all selectors in the list
   contain a nesting selector */
```

But the plugin compiles it to:
```css
.foo {
    color: red;
}

.foo .bar, .baz {
    color: blue;
}
```
