### ISSUE TITLE
An empty rule is created if If there's no property before a nested rule

### ISSUE THREAD

**Issue by alienlebarge** [jonathantneal/postcss-nesting#19]
Hi,

If a root rules doesn't contain any property before the nest rule, it create an empty rule. Just wanted to know why ?

_input.css_

``` css
a {
    &:hover {
        color: purple;
    }
}
```

_actual.css_

``` css
a {
}

a:hover {
    color: purple
}
```

_expected.css_

``` css
a:hover {
    color: purple
}
```

---

if I refer to _exemple 1_ and _exemple 2_ in the [specs](http://tabatkins.github.io/specs/css-nesting/#motivation), the following code

``` css
table.colortable {
  & td {
    text-align:center;
    &.c { text-transform:uppercase }
    &:first-child, &:first-child + td { border:1px solid black }
  }
  & th {
    text-align:center;
    background:black;
    color:white;
  }
}
```

should become

``` css
table.colortable td {
  text-align:center;
}
table.colortable td.c {
  text-transform:uppercase;
}
table.colortable td:first-child, table.colortable td:first-child+td {
  border:1px solid black;
}
table.colortable th {
  text-align:center;
  background:black;
  color:white;
}
```

but in fact, it add `table.colortable {}` empty rule

``` css
table.colortable {
}

table.colortable td {
    text-align: center;
}

table.colortable td.c {
    text-transform: uppercase;
}

table.colortable td:first-child, table.colortable td:first-child + td {
    border: 1px solid black;
}

table.colortable th {
    text-align: center;
    background: black;
    color: white;
}
```

---

_by the way, thanks for all the great things you do for the community ..._ 👏

**Comment by stefan-kern** [comment]
this issue is the reason i can't use this plugin (have to use postcss-nested) at the moment . i really would hope for this to get fixed, so i tried to come up with a pull request on my own. i'm a bit lost since i never worked with postcss plugins before.

```
var hasDeclaration = false;
for (var i = 0; i < rule.nodes.length; i++) {
	if (rule.nodes[i].constructor.name === 'Declaration') {
		hasDeclaration = true;
	}
}

if (!hasDeclaration) {
	rule.remove();
}
```

in postcss-nesting/index.js:43 was my approach, which worked fine for the most part, but the rule.remove() seems to skip subsequent nestings. i.e:

```
.a {
  &.b {
    color: #111;
    &.c {
      color: #222;
    }
  }
  &.d {
    color: #333;
  }
}
```

becomes 

```
.a.b {
    color: #111
}
.a.b.c {
    color: #222
}
```

note: the last semi colon is also getting lost, i created a seperate issue for that: https://github.com/jonathantneal/postcss-nesting/issues/20

**Comment by Avol-V** [comment]
I have the same issue. Even in this simple example:
```css
div
{
	&
	{
		margin: 0;
	}
}
```
becomes
```css
div
{
}
div
{
    margin: 0
}
```
