### ISSUE TITLE
[doc] @nest with several rules/selectors

### ISSUE THREAD

**Issue by brillout** [jonathantneal/postcss-nesting#22]
From reading the doc I was expecting following to work

``` css
div {
  @nest .c1 &,
  @nest .c2 & {
    color: red;
  }
}
```

but the correct usage is

``` css
div {
  @nest
  .c1 &,
  .c2 & {
    color: red;
  }
}
```

A note or example about that would have saved me 30mn.

Thanks for `postcss-nesting` btw, I really like it.
