### ISSUE TITLE
Nested @media queries not in spec

### ISSUE THREAD

**Issue by keithjgrant** [jonathantneal/postcss-nesting#24]
According to the docs, this supports using `@media` rules as a nested selector:

```
a, b {

    @media (min-width: 30em) {
        color: yellow;
    }
}
```

However, I don’t see this anywhere in the [editor’s draft](http://tabatkins.github.io/specs/css-nesting/). I’m not sure if this was pulled from the spec or just added here as a bonus, but this should probably be called out in the documentation (or removed entirely if the intent is to follow the spec as closely as possible).

**Comment by jonathantneal** [comment]
Good question. @tabatkins, is there intent to allow for nested `@media`?

**Comment by tabatkins** [comment]
Yes, tho that's not part of my Nesting proposal per se; we already have the fact that at-rules are allowed to next inside of style rules (per spec), we just haven't yet defined any at-rules that are valid in there.  But yeah, in an ideal world @media would nest like that.

**Comment by wbyoung** [comment]
@tabatkins @jonathantneal one thing that may be worth considering. Nesting media queries can become somewhat tricky. Given the following:

```css
a, b {
    @media (min-width: 30em) {
        color: yellow;
        @media (max-width: 60em) {
            color: cyan;
        }
    }
}
```

This plugin appears to produce:

```css
a, b {
}

@media (min-width: 30em) {
    a, b {
        color: yellow;
    }
}

@media (min-width: 30em) and (max-width: 60em) {
    a, b {
        color: cyan;
    }
}
```

That's all well and good, but these queries omit the optional _type_ and _negation_ prefix. So you can't really do something like:

```css
a, b {
    @media (min-width: 30em) {
        color: yellow;
        @media not (max-width: 60em) {
            color: cyan;
        }
    }
}
```

Because the resulting CSS isn't really correct:

```css
@media (min-width: 30em) and not (max-width: 60em) {
    a, b {
        color: cyan;
    }
}
```

I don't know what you want to do about this, but perhaps it may be best to have this plugin block multiple levels of media query nesting for now as the spec doesn't cover it and it can't always be done correctly.
