### ISSUE TITLE
{ Error: undefined:3:27389: missing '}'

### ISSUE THREAD

**Issue by cmnstmntmn** [jonathantneal/postcss-nesting#27]
```css
.nav-trigger {
  .Site-header {
      .Navigation-menu {
        color:red;      
      }
  }
}
```

```js
  reason: 'missing \'}\'',
  filename: undefined,
  line: 3,
  column: 27389,
  source: '~.Site-header .Navigation-menu{color:red}}' }
```

switched to `postcss-nested` fixed the problem

**Comment by tbremer** [comment]
This plugin requires the use of ampersands `&` or the at-rule and ampersand `@nest &`

IE:

```css
.nav-trigger {
  & .Site-header {
      & .Navigation-menu {
        color:red;      
      }
  }
}
```

produces:

```css
.nav-trigger {
}

.nav-trigger .Site-header {
}

.nav-trigger .Site-header .Navigation-menu {
    color: red;
}
```

You can test the plugin at: http://jonathantneal.github.io/postcss-nesting/
