### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by Semigradsky** [jonathantneal/postcss-nesting#32]
Input:
```css
.button {
  & i {
    color: black;
  }
}
```

Expected output: (2 spaces)
```css
.button i {
  color: black
}
```

Actual output: (4 spaces)
```css
.button i {
    color: black
}
```

**Comment by jonathantneal** [comment]
Your examples are formatted in a way that makes it hard for me to understand. Your nested selector is indented, so you might expect:

```css
.button {}

  .button i {
    color: black;
  }
```

However, this plugin does not preserve empty nesting containers, and it strips the raw spacing around generated nodes so that they match the formatting of the selectors around them.

This is a spacing compromise, because people expect their nesting blocks to match the indentation of the nesting block’s parent’s indentation, and they don’t expect empty blocks coming before their nesting blocks.

Does this make sense? Concerns? Otherwise, I will close this.

**Comment by Semigradsky** [comment]
Ok, another example.

Input:
```css
.button {
  color: white;
  & i {
    color: black;
  }
}
```

Expected and actual output:
```css
.button {
  color: white
}
.button i {
  color: black
}
```

Now `color: black` has correct indentation (2 spaces), but in previous example 4 spaces.

**Comment by jonathantneal** [comment]
I see. The issue here is that postcss is normalizing the raws of declarations, and since `.button` is removed in the first example. `.button i` must rely on however PostCSS determines the raws should be. To be honest, I have never understood how spacing is determined in PostCSS. Also, I’m unsure how we should expect indentation to be? Why do we expect to de-ident the blocks at all? It would help if we could ping someone familiar with raws / spacing from the PostCSS team. @ai, any suggestions?

**Comment by ai** [comment]
There is a two ways:

1. Add a code to fix `raws.before`.
2. Ignore this problem and ask users to use any CSS formatter.

**Comment by Semigradsky** [comment]
And one more example.

Input:
```css
.button {
  & i {
    color: black;
  }
  color: white;
}
```

Expected output: (2 spaces)
```css
.button i {
  color: black
}
.button {
  color: white
}
```

Actual output: (4 spaces)
```css
.button i {
      color: black
}
.button {
    color: white
}
```
