### ISSUE TITLE
postcss-import breaks ordering

### ISSUE THREAD

**Issue by denis-kalinichenko** [jonathantneal/postcss-nesting#33]
This code:

`primary.css`

```css
:root {
  --primary: {
    background: blue;
    color: white;

    &:hover {
      background: red;
    }

    &:active {
      background: pink;
    }
  };
}
```

`Button.css`
```css
@import "./primary.css";

.__base {
  appearance: none;
  border: none;
  border-radius: 3px;

  &:hover {
    text-decoration: none;
  }

  &:focus {
    outline: none;
  }

  &::-moz-focus-inner {
    border: 0;
  }
}

.--primary {
  composes: __base;
  @apply --primary;
}
```

is compiled to:
```css
.Button--primary:active{
      background: #008ecc
}.Button__base {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  border: none;
  border-radius: 3px
}

.Button__base:hover{
      text-decoration: none
}

.Button__base:focus{
      outline: none
}

.Button__base::-moz-focus-inner{
      border: 0
}

.Button--primary {
    background: #008ecc;
    color: #fff;
}

.Button--primary:hover{
      background: #056aab
}
```

As you can see, `.Button--primary:active` should be at the bottom of document. Maybe [postcss-import](https://github.com/postcss/postcss-import) breaks ordering IMO. 

Tools: webpack 2, css-loader, postcss-loader, latest postcss-nesting@3.0.0
