### ISSUE TITLE
on v4.0.0 some nesting forms are not allowed anymore

### ISSUE THREAD

**Issue by cloud-walker** [jonathantneal/postcss-nesting#34]
On my stack I use BEM and I usually nest like this:

```CSS
.header {
  position: relative;
  background: $color-primary;
  border-bottom: solid 1px rgba(255, 255, 255, 0.15);

  &__container {
    display: flex;
    align-items: center;
    min-height: calc($spacing-unit * 3);
    @mixin container;

    @media screen and (max-width: $width-md) {
      flex-wrap: wrap;
      padding: 0 $spacing-small;
    }
  }
```

But v4.0.0 it seems to break support of this form of nesting, and the Changelog says only this:
![schermata 2017-05-22 alle 11 46 12](https://cloud.githubusercontent.com/assets/1144075/26302381/512d2dde-3ee4-11e7-90a2-66ee60c3018f.png)

What I'm doing wrong?
