### ISSUE TITLE
Nested query media was promoted

### ISSUE THREAD

**Issue by Oscar-ren** [jonathantneal/postcss-nesting#35]
Hi, i use postcss-cssnext nesting feature to nesting the media query, but the result css media query was promoted.

there is the code

```css
.left_column {
  position: fixed;
  width: 250px;
  height: 100%;
  background: #00ccff;
  color: var(--mainColor);

  & header {
    padding-top: 60px;
  }

  @media screen and (max-width: 1024px) {
    width: 210px;
  }
}
```

> result

```css
@media screen and (max-width: 1024px) {
  .left_column {
    width: 210px;
  }
}
.left_column {
   position: fixed;
   width: 250px;
   height: 100%;
   background: #00ccff;
   color: white
}
```
the media query before `.left_column`,  make the media query be overwritten

when i remove `& header {}` ,the result is my expected

```css
.left_column {
   position: fixed;
   width: 250px;
   height: 100%;
   background: #00ccff;
   color: white
}

@media screen and (max-width: 1024px) {
  width: 210px;
}
```

is there anything wrong? thanks

my code environment is 
![image](https://cloud.githubusercontent.com/assets/9464221/26386370/faeaf0c8-4078-11e7-8df4-13141d8869a2.png)
