### ISSUE TITLE
trailing semicolon missing for the last rule of root element

### ISSUE THREAD

**Issue by wvfan** [jonathantneal/postcss-nesting#39]
The input `styles.css`
```css
:local(.styles) {
  width: 500px;
  height: 300px;
  background-image: url(images/login-background.jpg);
  background-size: cover;
  background-color: blue;
  & > .aa {
    background-color: red;
  }
}
```

the output 

```css
.styles_styles_xOQ {
  width: 500px;
  height: 300px;
  background-image: url(http://localhost:3000/dist/4cacff6a01b1d1e4aedda554d4711417.jpg);
  background-size: cover;
  background-color: blue
}
.styles_styles_xOQ > .aa{
  background-color: red;
}
```

As a result, the browser failed to recognize the rules for the first selector.
