### ISSUE TITLE
Not all @nest at-rules are transformed

### ISSUE THREAD

**Issue by priver** [jonathantneal/postcss-nesting#40]
Version of postcss-nesting: 4.0.1

Input:
```css
.a {
  color: black;
  @nest .a1 & {color: red;}
  @nest .a2 & {color: blue;}
  @nest .a3 & {color: green;}
  @nest .a4 & {color: yellow;}
}

.b {
  color: black;
  @nest .b1 & {color: red;}
  @nest .b2 & {color: blue;}
  @nest .b3 & {color: green;}
  @nest .b4 & {color: yellow;}
}
```

Output:
```css
.a {
  color: black
}

.a1 .a {
  color: red
}

.a2 .a {
  color: blue
}

.a {

  @nest .a3 & {color: green;
  }

  @nest .a4 & {color: yellow;
  }
}

.b {
  color: black;
  @nest .b1 & {color: red;}
  @nest .b2 & {color: blue;}
  @nest .b3 & {color: green;}
  @nest .b4 & {color: yellow;}
}
```

Expected:
```css
.a {
  color: black
}

.a1 .a {
  color: red
}

.a2 .a {
  color: blue
}

.a3 .a {
  color: green
}

.a4 .a {
  color: yellow
}

.b {
  color: black
}

.b1 .b {
  color: red
}

.b2 .b {
  color: blue
}

.b3 .b {
  color: green
}

.b4 .b {
  color: yellow
}
```

**Comment by woble** [comment]
Any update on this? :thinking:

**Comment by woble** [comment]
Here's another simplified example that doesn't work with the latest version.

Input

```css
::-webkit-scrollbar {
    @nest
    body:not(.macos) & {
        background-color: white;
    }

    @nest
    .secondary & {
        @nest
        body:not(.macos) & {
            background-color: black;
        }
    }

    @nest
    .primary & {
        @nest
        body:not(.macos) & {
            background-color: white;
        }
    }
}
```

Output

```css
body:not(.macos) .foo {
    background-color: white
}

.foo {
    @nest .secondary & {
        @nest body,
        not(.macos) & {
            background-color: black
        }
    }
    @nest .primary & {
        @nest body,
        not(.macos) & {
            background-color: white
        }
    }
}
```
