### ISSUE TITLE
Nested BEM selectors not unwrapping

### ISSUE THREAD

**Issue by krambuhl** [jonathantneal/postcss-nesting#41]
It appears that version `4.0` requires whitespace between the ampersand and nested selectors.  This breaks a pattern that we have adopted for BEM style naming conventions, which had been working on the `3.0` releases.

It looks like the rule validation was the major change from 3 and 4.  I was unable to decipher if this is valid based on the written spec. 

Is this the expected results? 

Input:

```css
.box {
  & a { color: pink; }

  &__element {
    color: red;
  }

  &--modifier {
    color: yellow;

    & a {
      color: green;

      &:hover { text-decoration: underline; }
    }
  }
}
```

Output:
```css
.box a {
    color: pink;
}
.box {
    &__element { color: red; }
    &--modifier { color: yellow; }
    &--modifier a { color: green; }
    &--modifier a:hover { text-decoration: underline; }
}
```
