### ISSUE TITLE
Does it support `& > .foo` ?

### ISSUE THREAD

**Issue by xcatliu** [jonathantneal/postcss-nesting#48]
In the [spec](http://tabatkins.github.io/specs/css-nesting/#direct), this should be supported:

```css
.foo {
  color: blue;
  & > .bar { color: red; }
}
/* equivalent to
   .foo { color: blue; }
   .foo > .bar { color: red; }
 */
```

But I tried this plugin, it's not supported.
