### ISSUE TITLE
Trailing semicolon cause some plugin's translate failed

### ISSUE THREAD

**Issue by Akimyou** [jonathantneal/postcss-nesting#52]
I use postcss-nesting => px2rem. This px2rem plugin use semicolon to determine how to translate px unit. 

For example

Source

```css
.app {
  height: 100px; /*no*/
  & .hello {
    height: 100px; /*no*/
    height: 'PX2REM NO BUG';
  }
}
```
After postcss-nesting

```css
.app {
  height: 100px /*no*/
}

.app .hello {
  height: 100px;

  /*no*/
  height: 'PX2REM NO BUG'; }
```

Than px2rem cannot resolve  `height: 100px /*no*/`( semicolon missing ). After px2rem

```css
.app {
  height: 1.333333rem;  /* incorrect */
}

.app .hello {
  height: 100px;
  height: 'PX2REM NO BUG';
}
```

https://github.com/songsiqi/px2rem

Do you have some ideal for resolve this problem?

Thank You! 39
