### ISSUE TITLE
Cannot nest more than one level deep.

### ISSUE THREAD

**Issue by keithamus** [jonathantneal/postcss-nesting#6]
### Summary

When trying to nest more than one level deep, the plugin ignores nested selectors, and they appear nested in the output.

### Example 1:

Given the following post-CSS:

#### input
```css
.a {
  color: blue;
  {
    .b {
      color: blue;
      {
        .c {
          color: blue;
        }
      }
    }
  }
}
```

I'd expect to see the the following:

#### expected
```css
.a {
  color: blue;
}
  .a .b {
    color: blue;
  }
    .a .b .c {
      color: blue;
    }
```

Instead I get:

#### actual
```css
.a {
  color: blue
}
        .a .c {
          color: blue;
        }
    .a .b {
      color: blue;
      .a {
        .a .c {
          color: blue;
        }
      }
    }
      .a {
        .a .c {
          color: blue;
        }
      }
```

### Example 2

This is from the [spec](https://tabatkins.github.io/specs/css-nesting/#the-nested-block) (example #4):

#### input
```css
  div, p {
    font-size: 10px;
    {.keyword {color: green;}}
    {.constant {
      color: red;
      background-color: green;
      {&:hover::after { content: " [" attr(value) "]";}}
    }}
  }
```

#### expected
```css
  div, p {font-size: 10px;}
  div .keyword, p .keyword {color: green;}
  div .constant, p .constant {color: red; background-color: green;}
  div .constant:hover::after, p .constant:hover::after {content: " [" attr(value) "]";}
```

#### actual
```css
div, p {
  font-size: 10px
}div:hover::after, p:hover::after { content: " [" attr(value) "]";}div .constant, p .constant {
    color: red;
    background-color: green;
    div , p {div:hover::after, p:hover::after { content: " [" attr(value) "]";}}
  }div .keyword, p .keyword {color: green;}
    div , p {div:hover::after, p:hover::after { content: " [" attr(value) "]";}}
```
