### ISSUE TITLE
Multiple @nest in combined selector don't transform

### ISSUE THREAD

**Issue by daanvosdewael** [jonathantneal/postcss-nesting#62]
Input:

```css
.a {
    display: flex;

    @nest .foo &,
    @nest .bar & {
        color: #fff;
    }
}
```

Output:

```css
.a {
    display: flex;
}

.foo .a,
@nest .bar .a {
    color: #fff;
}
```

Expected:

```css
.a {
    display: flex;
}

.foo .a,
.bar .a {
    color: #fff;
}
```

The second `@nest` is not transformed. This issue is different than #40 because the `@nest` selectors are combined with a comma.

Versions:
- postcss: 7.0.6
- postcss-nesting: 7.0.0

**Comment by jonathantneal** [comment]
Hello, the issue you are experiencing is due to syntax. `@nest` is not repeated between selectors. What you want to write is:

```pcss
.a {
    display: flex;

    @nest .foo &, .bar & {
        color: #fff;
    }
}
```

**Comment by daanvosdewael** [comment]
I do still have an issue with the `@nest` rule. Consider the following:

Input:
```postcss
.a {
    display: flex;

    &.b &,                  /* <-- added this line */
    @nest .foo &, .bar & {
        color: #fff;
    }
}
```

Output:
```css
.a {
    display: flex;

    &.b &,
    @nest .foo &, .bar & {
        color: #fff;
    }
}
```

Expected:
```css
.a {
    display: flex;
}

.a.b,
.foo .a,
.bar .a {
    color: #fff;
}
```

I know it's an edge case, but would it be possible to make this work? I'm currently working on a codebase where I don't have control over the HTML, so I have to get creative with the selectors ;)
