### ISSUE TITLE
Support for CSS @apply Rule

### ISSUE THREAD

**Issue by JosefJezek** [jonathantneal/postcss-nesting#7]
I can not use `postcss-apply` and `postcss-custom-properties`. This features are implemented in Polymer using JS. I get error

```css

:root {
  /* Primary colors */
  --dark-primary-color:         var(--paper-indigo-700);
  --default-primary-color:      var(--paper-indigo-500);
  --light-primary-color:        var(--paper-indigo-100);
  --text-primary-color:         #fff; /* text / icons */

  /* Accent colors */
  --accent-color:               var(--paper-pink-a200);
  --text-accent-color:          #fff; /* text / icons */

  /* Background colors */
  --primary-background-color:   var(--paper-grey-50);
  --secondary-background-color: #fff;

  /* Text colors */
  --primary-text-color:         var(--paper-grey-900);
  --secondary-text-color:       var(--paper-grey-600);
  --disabled-text-color:        var(--paper-grey-400);

  /* Other colors */
  --divider-color:              var(--paper-grey-300);
}

.Main {
  background: var(--primary-background-color);

  @nest &-content {
    color: var(--primary-text-color);
    @media (max-width: 599px) {
      @apply(--paper-font-body);
    }
    @media (min-width: 600px) {
      @apply(--paper-font-body2);
      padding: 48px 62px;
    }
  }
}
```
->

`Error: no writecb in Transform class`

**Comment by ai** [comment]
This error seems like irrelevant to PostCSS. Looks like as wrong node.is Stream usage. Do you use Gulp?

**Comment by JosefJezek** [comment]
Yes, gulp. Output is ok without error when remove lines contain `@apply` rule from css.

**Comment by ai** [comment]
Can you post a your Gulpfile and error stacktrace?

**Comment by JosefJezek** [comment]
Sorry, my issue. Thank you.

I found new 2 issues

```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
    @media (--md-viewport) {
      @apply(--paper-font-body2);
      padding: 48px 62px;
    }
  };
}
```
->
```css
@media (min-width: 600px) {
  @apply(--paper-font-body2);
  padding:         48px 62px;
}
```

```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  };
}
```
-> Missing `;` on `@apply` rule
```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  }
}
```
