### ISSUE TITLE
Nesting media queries

### ISSUE THREAD

**Issue by rstacruz** [jonathantneal/postcss-nesting#9]
It seems you can't nest media queries:

```css
.main {
  @media (min-width: 100px) {
    color: blue;
    @media (min-device-pixel-ratio: 1.5) {
      color: red;
    }
  }
}
```

you get:

```css
.main {
}

@media (min-width: 100px) {
    .main {
        color: blue;
    }

    @media (min-device-pixel-ratio: 1.5) {
        .main {
            color: red;
        }
    }
}
```

but I'd expect instead:

```css
@media (min-width: 100px) and (min-device-pixel-ratio: 1.5) {
  .main {
    color: red;
  }
}
```

**Comment by jonathantneal** [comment]
I think this would require feedback from @TabAtkins. The specification doesn’t mention nesting `@media` queries or how they should be handled. https://tabatkins.github.io/specs/css-nesting/

**Comment by tabatkins** [comment]
Nesting MQs is separate from nesting style rules.  It'll come in time.

That said, this:

```css
.main {
  @media (min-width: 100px) {
    color: blue;
    @media (min-device-pixel-ratio: 1.5) {
      color: red;
    }
  }
}
```

should desugar to:

```css
@media (min-width: 100px) {
  .main { color: blue; }
}
@media (min-width: 100px) and (min-device-pixel-ratio: 1.5) {
  .main { color: red; }
}
```

if you're handling nested MQs.  (It's also acceptable to have the second one be two separate `@media` rules nested inside each other, like you'd have if you combined `@media` and `@support` or something.)

**Comment by stevenvachon** [comment]
Is this valid CSS?:
```css
body {
  @medida (width > 500) {
    color: transparent;
  }
}
```
I can't find it in any spec but it's supported by this plugin.

**Comment by tabatkins** [comment]
Currently no, but I need to add it to my Nesting proposal when I have time.  There's nothing wrong with this type of nesting, and it can be quite useful.

**Comment by MoOx** [comment]
@jonathantneal I think we can close this issue.

**Comment by jonathantneal** [comment]
@rstacru, since @tabatkins is adding nesting mqs to the nesting proposal, I have added it to the [v2.2.0](https://github.com/jonathantneal/postcss-nesting/tree/v2.2.0). Enjoy!

**Comment by stevenvachon** [comment]
I'm weary about these features.. they're not part of any public spec -- they're only part of a proposal from one person. For this reason, I still use Less.js as a pre-processor.

**Comment by jonathantneal** [comment]
@stevenvachon, this plugin does not "support" `@media (width > 500)`. This plugin supports nested rules and at-rules that follow Tab's spec as well as his additional expectations from this thread.

What you are experiencing is the result of another spec and another plugin that, when combined with this plugin through cssnext, are adding the support you describe. So, to be clear, the media queries you described are outside the scope of this plugin and the spec I am following.

See https://github.com/postcss/postcss-media-minmax and https://drafts.csswg.org/mediaqueries/ if you wish to express weariness over those features.

Tab's work here is generally considered to be the authoritative proposal for nested queries, and he is the author of other implemented specs.

**Comment by stevenvachon** [comment]
I'm not experiencing any issue. Those are plugins and can be chosen to be used or not, but as part of cssnext, I would wager that they shouldn't be included. But Less.js handles these things for me anyway and makes more sense to me having that logic performed there until Tab's proposals become at least a draft spec.

**Comment by jonathantneal** [comment]
I would be open to a feature that toggles buy in of the nested media queries within nested media queries, as the spec is not entirely clear as to how these are handled yet.

I believe it's implied they should combine similar to selectors: media queries split into sets along the comma, and then each nested set combines with the ancestor set.

```css
@media screen, print {
  @media (min-width: 30em) {
    color: blue;
  }
}
```

Resolves to:

```css
@media screen and (min-width: 30em), print and (min-width: 30em) {
  color: blue;
}
```
